<html>
	<body>
		<p> Dear Finance Team,</p>
		<p> The feedfile dated <?php echo $feedfile_date; ?> has been generated by the dealer portal system and attached for your kind reference.</p>
		<p> Thanks & Regards </p>
		<p> Time dotCom Dealer Portal. </p>
	</body>
</html>



