<?php

	
	$SHOP_TITLE 					= 	trim(getenv('SHOP_TITLE'));
	$ADMIN_NAME 					=  	trim(getenv('ADMIN_NAME'));	
	$SUBMIT_PROOF_EMAIL_SUBJECT 	=  	trim(getenv('SUBMIT_PROOF_EMAIL_SUBJECT'));
	$ORDER_CONFIRMATION_SUBJECT 	=  	trim(getenv('ORDER_CONFIRMATION_SUBJECT'));
	$RESUBMIT_REQUEST_EMAIL_SUBJECT =  	trim(getenv('RESUBMIT_REQUEST_EMAIL_SUBJECT'));
	$RESUBMIT_PROOF_EMAIL_SUBJECT 	=  	trim(getenv('RESUBMIT_PROOF_EMAIL_SUBJECT'));
	$CASH_TAX_INVOICE_EMAIL_SUBJECT =  	trim(getenv('CASH_TAX_INVOICE_EMAIL_SUBJECT'));
	
	
	$config = array(
		'Settings' => array(
			'SHOP_TITLE' => '',
			'ADMIN_NAME' => '',
			'SUBMIT_PROOF_EMAIL_SUBJECT' => '',
			'ORDER_CONFIRMATION_SUBJECT' => '',
			'RESUBMIT_REQUEST_EMAIL_SUBJECT' => '',
			'RESUBMIT_PROOF_EMAIL_SUBJECT' => '',
			'CASH_TAX_INVOICE_EMAIL_SUBJECT' => '.',
		)
	);


